### ISSUE TITLE
Error with Heroku:20 stack

### ISSUE THREAD

**Issue by alexblueskypilot** [fagiani/apt-buildpack#14]
Hi,

I have this error when building with the Heroku:20 stack on buildpacks.io:
 [413] => -----> Detected Aptfile changes, flushing cache
    [414] => cp: cannot stat 'Aptfile': No such file or directory

The Aptfile is present and seems to be detected and the buildpack installed.

Do you know what I did wrong?

Thanks!

**Comment by fagiani** [comment]
Hey @alexblueskypilot!

Thanks a bunch for reporting this bug!

I was unable to reproduce such error but browsing topics that mention similar errors it looks like it has to do with the way `cp` command handles double quotes as you can see here:

https://github.com/fagiani/apt-buildpack/blob/fa1a3a5c312191eb62abd51306aa08f8c89b6a5e/bin/build#L73

This is actually a port of a heroku buildpack that I converted "as is" to a CNB buildpack and therefore it must have slipped by.

I've created [this PR](https://github.com/fagiani/apt-buildpack/pull/15) #15  in order to fix it but it would be nice if you could give it a try before i release it.

Can you clone this project locally and switch to the PR's branch and point the buildpack to load from a path (something like `pack build ... --buildpack /path/to/the/cloned/repo ...`) and check it works?

Once you validate it i will promptly release a new version.

Let me know if you need further help with testing!

**Comment by alexblueskypilot** [comment]
Hi @fagiani 

Sorry for the delay, yes it seems to be working with this PR. Can you merge it?

Thanks!
