### ISSUE TITLE
Apt install without sudo?

### ISSUE THREAD

**Issue by enricorotundo** [fagiani/apt-buildpack#7]
I'm definitely missing something but how come this buildpack can run [apt-get install](https://github.com/fagiani/apt-buildpack/blob/a24f932a4129f4389254203915be3f23f870ffe3/bin/build#L97) without sudo? Most buildpack-related docs I've seen so far make very clear buildpacks can't install arbitrary OS packages using apt. What magic is happening here? 😅

**Comment by fagiani** [comment]
@enricorotundo I am not sure if I understood your question. Is it just a curiosity about how it works or would you be missing the `sudo` capability in order to install a specific `apt` package?

If it is the first, I believe in build time it is not required to be used as the user which is running within the container is privileged enough to do it like if it was root.

If it is the later, please share a bit more about your issue and I may be able to help you further.

**Comment by enricorotundo** [comment]
It's the first. This issue probably fits better in the [heroku/pack-images](https://github.com/heroku/pack-images) repo but since we're here I'll just shoot it. 

The `heroku` user can run [`apt-get update` in this buildpack](https://github.com/fagiani/apt-buildpack/blob/a24f932a4129f4389254203915be3f23f870ffe3/bin/build#L86 ), however, if I run the resulting container with `docker run --rm  -it --user="heroku" --entrypoint /bin/bash my-demo-app` and try to apt-get update it'd fail with `List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)`. How come?

The broader question is... how are user & permissions managed in buildpacks? Maybe @fagiani knows?

**Comment by fagiani** [comment]
Ciao @enricorotundo!

As far as I understand, `buildpacks` are only one piece of the puzzle, there are also [`stacks`](https://buildpacks.io/docs/concepts/components/stack/) and [`builders`](https://buildpacks.io/docs/concepts/components/builder/) and a `builder` will be composed of a `build` and `run` image. Not everything on a build phase will be available at runtime as they're different environments and most libs and sources will get pruned in order to decrease image size and reduce surface for possible attacks with unused code. AFAIK, a runtime image is meant to be immutable and no updates shall be made after they're created. 

Would you have any concrete case that require those updates at runtime and not at build time or you're more into the science/philosophy discovery side?

If you happen to be missing any of the binaries that were supposed to be available at runtime, you could try using [`launcher`](https://buildpacks.io/docs/app-developer-guide/run-an-app/#run-a-multi-process-app), which is standard to all created images, with a command like this:

    $ docker run --rm --entrypoint launcher -it my-demo-app bash

and that should stage all your environment settings and source all intended binaries on path for you.

As of your broader question I confess that I do not have a deep understanding about that other than they will run in a controlled environment that is not meant to be changed. Maybe a good channel to discuss this further is the [CNCF Community Slack](https://buildpacks.io/community/) as most of the maintainers hang out there!

If you have any business needs you need help to solve please feel free to reach out in private.
